@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor Web_client

Web_client -> app.reponse2request: http-request (GET)
app.reponse2request -> globals.GLOBALS_init
app.reponse2request -> app.__inspect_IS_document
app.__inspect_IS_document -> app.__get_document_page_link
app.__inspect_IS_document -> app.__get_downloaded_document
app.__inspect_IS_document -> app.__get_head_hash
app.__inspect_IS_document -> app.__get_document_link
app.__inspect_IS_document -> app.__get_downloaded_document
alt downloaded_IS_document.status_code == 404
    app.__inspect_IS_document -> app.APP_text_document_not_found
end

app.reponse2request -> html_dashboard.get_page_html
group Renderar dashboard-html
html_dashboard.get_page_html -> html_dashboard.__html_start
html_dashboard.get_page_html -> html_dashboard.__html_head
html_dashboard.get_page_html -> html_dashboard.__html_body_start
html_dashboard.get_page_html -> html_dashboard.__html_sidebar
html_dashboard.get_page_html -> html_dashboard.__html_overview_start
html_dashboard.get_page_html -> html_dashboard.__html_summary_infospec
html_dashboard.__html_summary_infospec -> html_dashboard.__text_document_not_found
html_dashboard.__text_document_not_found -> repo.REPO_get_domain_docs_link
html_dashboard.get_page_html -> html_dashboard.__html_summary_TKB
html_dashboard.get_page_html -> html_dashboard.__html_section_end
html_dashboard.get_page_html -> html_dashboard.__html_detail_section_begin
html_dashboard.get_page_html -> html_dashboard.__html_recent_inspection_box_begin
html_dashboard.get_page_html -> html_dashboard.__html_recent_inspection_box_end
html_dashboard.get_page_html -> html_dashboard.__html_detail_box_begin_TKB
html_dashboard.get_page_html -> html_dashboard.__box_content_end
html_dashboard.get_page_html -> html_dashboard.__html_section_end
html_dashboard.get_page_html -> html_dashboard.__html_body_end
html_dashboard.get_page_html -> html_dashboard.__html_end
end

app.reponse2request -> Web_client: http-response (html))
@enduml