@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor Web_client

Web_client -> app.reponse2request: http-request (GET)
app.reponse2request -> globals.GLOBALS_init
app.reponse2request -> app.__inspect_IS_document
app.__inspect_IS_document -> app.__get_document_page_link
app.__inspect_IS_document -> app.__get_downloaded_document
app.__inspect_IS_document -> app.__get_head_hash
app.__inspect_IS_document -> app.__get_document_link
app.__inspect_IS_document -> app.__get_downloaded_document

app.reponse2request -> html_dashboard.get_page_html
group Renderar dashboard-html
html_dashboard.get_page_html -> html_dashboard.__html_summary_infospec
html_dashboard.__html_summary_infospec -> html_dashboard.__text_document_not_found
html_dashboard.__text_document_not_found -> repo.REPO_get_domain_docs_link
html_dashboard.get_page_html -> html_dashboard.__html_summary_TKB
end

app.reponse2request -> Web_client: http-response (html))
@enduml